# This file has been autogenerated by the pywayland scanner

# Copyright © 2019 Purism SPC
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice (including the next
# paragraph) shall be included in all copies or substantial portions of the
# Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.

from __future__ import annotations

from pywayland.protocol_core import (
    Argument,
    ArgumentType,
    Global,
    Interface,
    Proxy,
    Resource,
)

from ..wayland import WlOutput
from .zwlr_output_power_v1 import ZwlrOutputPowerV1


class ZwlrOutputPowerManagerV1(Interface):
    """Manager to create per-output power management

    This interface is a manager that allows creating per-output power
    management mode controls.
    """

    name = "zwlr_output_power_manager_v1"
    version = 1


class ZwlrOutputPowerManagerV1Proxy(Proxy[ZwlrOutputPowerManagerV1]):
    interface = ZwlrOutputPowerManagerV1

    @ZwlrOutputPowerManagerV1.request(
        Argument(ArgumentType.NewId, interface=ZwlrOutputPowerV1),
        Argument(ArgumentType.Object, interface=WlOutput),
    )
    def get_output_power(self, output: WlOutput) -> Proxy[ZwlrOutputPowerV1]:
        """Get a power management for an output

        Create an output power management mode control that can be used to
        adjust the power management mode for a given output.

        :param output:
        :type output:
            :class:`~pywayland.protocol.wayland.WlOutput`
        :returns:
            :class:`~pywayland.protocol.wlr_output_power_management_unstable_v1.ZwlrOutputPowerV1`
        """
        id = self._marshal_constructor(0, ZwlrOutputPowerV1, output)
        return id

    @ZwlrOutputPowerManagerV1.request()
    def destroy(self) -> None:
        """Destroy the manager

        All objects created by the manager will still remain valid, until their
        appropriate destroy request has been called.
        """
        self._marshal(1)
        self._destroy()


class ZwlrOutputPowerManagerV1Resource(Resource):
    interface = ZwlrOutputPowerManagerV1


class ZwlrOutputPowerManagerV1Global(Global):
    interface = ZwlrOutputPowerManagerV1


ZwlrOutputPowerManagerV1._gen_c()
ZwlrOutputPowerManagerV1.proxy_class = ZwlrOutputPowerManagerV1Proxy
ZwlrOutputPowerManagerV1.resource_class = ZwlrOutputPowerManagerV1Resource
ZwlrOutputPowerManagerV1.global_class = ZwlrOutputPowerManagerV1Global
