# This file has been autogenerated by the pywayland scanner

# Copyright © 2019 Purism SPC
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice (including the next
# paragraph) shall be included in all copies or substantial portions of the
# Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.

from __future__ import annotations

import enum

from pywayland.protocol_core import (
    Argument,
    ArgumentType,
    Global,
    Interface,
    Proxy,
    Resource,
)


class ZwlrOutputPowerV1(Interface):
    """Adjust power management mode for an output

    This object offers requests to set the power management mode of an output.
    """

    name = "zwlr_output_power_v1"
    version = 1

    class mode(enum.IntEnum):
        off = 0
        on = 1

    class error(enum.IntEnum):
        invalid_mode = 1


class ZwlrOutputPowerV1Proxy(Proxy[ZwlrOutputPowerV1]):
    interface = ZwlrOutputPowerV1

    @ZwlrOutputPowerV1.request(
        Argument(ArgumentType.Uint),
    )
    def set_mode(self, mode: int) -> None:
        """Set an outputs power save mode

        Set an output's power save mode to the given mode. The mode change is
        effective immediately. If the output does not support the given mode a
        failed event is sent.

        :param mode:
            the power save mode to set
        :type mode:
            `ArgumentType.Uint`
        """
        self._marshal(0, mode)

    @ZwlrOutputPowerV1.request()
    def destroy(self) -> None:
        """Destroy this power management

        Destroys the output power management mode control object.
        """
        self._marshal(1)
        self._destroy()


class ZwlrOutputPowerV1Resource(Resource):
    interface = ZwlrOutputPowerV1

    @ZwlrOutputPowerV1.event(
        Argument(ArgumentType.Uint),
    )
    def mode(self, mode: int) -> None:
        """Report a power management mode change

        Report the power management mode change of an output.

        The mode event is sent after an output changed its power management
        mode. The reason can be a client using set_mode or the compositor
        deciding to change an output's mode. This event is also sent
        immediately when the object is created so the client is informed about
        the current power management mode.

        :param mode:
            the output's new power management mode
        :type mode:
            `ArgumentType.Uint`
        """
        self._post_event(0, mode)

    @ZwlrOutputPowerV1.event()
    def failed(self) -> None:
        """Object no longer valid

        This event indicates that the output power management mode control is
        no longer valid. This can happen for a number of reasons, including: -
        The output doesn't support power management - Another client already
        has exclusive power management mode control   for this output - The
        output disappeared

        Upon receiving this event, the client should destroy this object.
        """
        self._post_event(1)


class ZwlrOutputPowerV1Global(Global):
    interface = ZwlrOutputPowerV1


ZwlrOutputPowerV1._gen_c()
ZwlrOutputPowerV1.proxy_class = ZwlrOutputPowerV1Proxy
ZwlrOutputPowerV1.resource_class = ZwlrOutputPowerV1Resource
ZwlrOutputPowerV1.global_class = ZwlrOutputPowerV1Global
